server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fooddelivery
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mySuperSecretKeyForFoodDeliveryJWTAuthentication123456
  expiration: 86400000